### ISSUE TITLE
Camera HAL

### ISSUE THREAD

**Issue by SpaceAgeHero** [kerneltoast/android_device_oneplus_onyx#2]
Please push camera enhancements to official branch of cm for onyx.

**Comment by pro5skate** [comment]
Hello Sultan! I'm not sure if this is allowed here, but is it okay for me to ask for an update on this ROM? Is it possible for you to make the Nught Mode from Oxygen OS available in this CM? I'm loving your ROM so much. Thanks!

**Comment by SpaceAgeHero** [comment]
No longer interested.
